### ISSUE TITLE
Bug: otn-kvm sonic-yanggen compile error

### ISSUE THREAD

**Issue by oplklum** [sonic-otn/sonic-buildimage#27]
### Is it platform specific

generic

### Importance or Severity

Critical

### Description of the bug

creating build/temp.linux-x86_64-cpython-313/build/temp.linux-x86_64-cpython-313
      x86_64-linux-gnu-gcc -I/sonic/platform/otn-kvm/sonic-yanggen/libyang-install/include -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_CFFI_NO_LIMITED_API -I/usr/include/python3.13 -c build/temp.linux-x86_64-cpython-313/_libyang.c -o build/temp.linux-x86_64-cpython-313/build/temp.linux-x86_64-cpython-313/_libyang.o -Werror -std=c99
      build/temp.linux-x86_64-cpython-313/_libyang.c:582:2: error: #error "This version of libyang bindings only works with libyang soversion 5.0.0+"
        582 | #error "This version of libyang bindings only works with libyang soversion 5.0.0+"
            |  ^~~~~
      build/temp.linux-x86_64-cpython-313/_libyang.c: In function ‘_cffi_d_lyd_any_value_str’:
      build/temp.linux-x86_64-cpython-313/_libyang.c:3918:32: error: incompatible type for argument 2 of ‘lyd_any_value_str’
       3918 |   return lyd_any_value_str(x0, x1, x2);
            |                                ^~
            |                                |
            |                                LYD_FORMAT
      In file included from /sonic/platform/otn-kvm/sonic-yanggen/libyang-install/include/libyang/context.h:23,
                       from /sonic/platform/otn-kvm/sonic-yanggen/libyang-install/include/libyang/libyang.h:27,
                       from build/temp.linux-x86_64-cpython-313/_libyang.c:578:
      /sonic/platform/otn-kvm/sonic-yanggen/libyang-install/include/libyang/tree_data.h:1179:78: note: expected ‘char **’ but argument is of type ‘LYD_FORMAT’
       1179 | LIBYANG_API_DECL LY_ERR lyd_any_value_str(const struct lyd_node *any, char **value_str);
            |                                                                       ~~~~~~~^~~~~~~~~
      build/temp.linux-x86_64-cpython-313/_libyang.c:3918:10: error: too many arguments to function ‘lyd_any_value_str’
       3918 |   return lyd_any_value_str(x0, x1, x2);
            |          ^~~~~~~~~~~~~~~~~
      /sonic/platform/otn-kvm/sonic-yanggen/libyang-install/include/libyang/tree_data.h:1179:25: note: declared here
       1179 | LIBYANG_API_DECL LY_ERR lyd_any_value_str(const struct lyd_node *any, char **value_str);
            |                         ^~~~~~~~~~~~~~~~~
      build/temp.linux-x86_64-cpython-313/_libyang.c: In function ‘_cffi_f_lyd_any_value_str’:
      build/temp.linux-x86_64-cpython-313/_libyang.c:3961:36: error: incompatible type for argument 2 of ‘lyd_any_value_str’
       3961 |   { result = lyd_any_value_str(x0, x1, x2); }
            |                                    ^~
            |                                    |
            |                                    LYD_FORMAT
      /sonic/platform/otn-kvm/sonic-yanggen/libyang-install/include/libyang/tree_data.h:1179:78: note: expected ‘char **’ but argument is of type ‘LYD_FORMAT’
       1179 | LIBYANG_API_DECL LY_ERR lyd_any_value_str(const struct lyd_node *any, char **value_str);
            |                                                                       ~~~~~~~^~~~~~~~~
      build/temp.linux-x86_64-cpython-313/_libyang.c:3961:14: error: too many arguments to function ‘lyd_any_value_str’
       3961 |   { result = lyd_any_value_str(x0, x1, x2); }
            |              ^~~~~~~~~~~~~~~~~
      /sonic/platform/otn-kvm/sonic-yanggen/libyang-install/include/libyang/tree_data.h:1179:25: note: declared here
       1179 | LIBYANG_API_DECL LY_ERR lyd_any_value_str(const struct lyd_node *any, char **value_str);
            |                         ^~~~~~~~~~~~~~~~~
      build/temp.linux-x86_64-cpython-313/_libyang.c: In function ‘_cffi_d_lyd_dup_siblings’:
      build/temp.linux-x86_64-cpython-313/_libyang.c:4245:31: error: passing argument 2 of ‘lyd_dup_siblings’ from incompatible pointer type [-Wincompatible-pointer-types]

### Steps to Reproduce

make target/sonic-otn-kvm.img.gz

### Actual Behavior and Expected Behavior

compile passed

### Relevant log output

```shell

```

### Output of `show version`, `show techsupport`

```shell

```
